In [25]:
import numpy as np
import pandas as pd

pd.Series(np.arange(4.0,step=1.0))

0    0.0
1    1.0
2    2.0
3    3.0
dtype: float64

In [26]:
import numpy as np
import pandas as pd

s1 = pd.Series(np.arange(4.0,step=1.0),index=['a','b','c','d'])

In [27]:
display(s1)
s1[0]

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

/tmp/ipykernel_25244/1551149800.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s1[0]


0.0

In [28]:
s1[['a','b','c','d']]

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [29]:
display(s1[-2:])
s1[-2:] * 2


c    2.0
d    3.0
dtype: float64

c    4.0
d    6.0
dtype: float64

In [30]:
s1[-2:] *= 2
s1

a    0.0
b    1.0
c    4.0
d    6.0
dtype: float64

In [32]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [34]:
np.reshape(np.arange(16),(8,2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [39]:
data = np.arange(16).reshape((4,4))
display(data)
dataFrame = pd.DataFrame(data,
             index = ['台北','台中','台南','高雄'],
             columns = ['one','two','three','four'])
dataFrame

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

one  two  three  four
台北    0    1      2     3
台中    4    5      6     7
台南    8    9     10    11
高雄   12   13     14    15